<?php

namespace Database\Seeders;

use App\Models\Pegawai;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = \Faker\Factory::create();
            DB::table('pegawais')->insert(array([
                'nip'                   =>  ' 4015028401',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  ' 4015028401',
                'nama'                  =>  'Anditha Ratnadhiyani, Ns.M.Kep., Sp.Kep.MB.',
                'slug'                  =>  'anditha-ratnadhiyani-nsmkep-spkepmb',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  1029048804,
                'id_prodi_homebase'     =>  'D14301',
                'nidn'                  =>  1029048804,
                'nama'                  =>  'Andra Saferi Wijaya, S.Kep., M.Kep., NERS.',
                'slug'                  =>  'andra-saferi-wijaya-skep-mkep-ners',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'keperawatan',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  1771044804870001,
                'id_prodi_homebase'     =>  'J13331',
                'nidn'                  =>  null,
                'nama'                  =>  'Ade Sissca Villia',
                'slug'                  =>  'ade-sissca-villia',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  1771086212900002,
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  1771086212900002,
                'nama'                  =>  'Ade Zayu Cempaka Sari',
                'slug'                  =>  'ade-zayu-cempaka-sari',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  2029127601,
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  2029127601,
                'nama'                  =>  'Adisel',
                'slug'                  =>  'adisel',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  3216206202940002,
                'id_prodi_homebase'     =>  'D13331',
                'nidn'                  =>  null,
                'nama'                  =>  'Ade Febryanti',
                'slug'                  =>  'ade-febryanti',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'promosi_kesehatan',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4002027501,
                'id_prodi_homebase'     =>  'E14401',
                'nidn'                  =>  4002027501,
                'nama'                  =>  'Asmawati, S.Kp., M.Kep.',
                'slug'                  =>  'asmawati-skp-mkep',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'keperawatan',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4007106801,
                'id_prodi_homebase'     =>  'E14401',
                'nidn'                  =>  4007106801,
                'nama'                  =>  'Agung Riyadi, Ns.S.Kep., M.Kes.',
                'slug'                  =>  'agung-riyadi-nsskep-mkes',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'keperawatan',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4009097102,
                'id_prodi_homebase'     =>  'E13451',
                'nidn'                  =>  4009097102,
                'nama'                  =>  'Agus Widada, S.KM., M.Kes.',
                'slug'                  =>  'agus-widada-skm-mkes',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'sanitasi',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4010066401,
                'id_prodi_homebase'     =>  'E14471',
                'nidn'                  =>  4010066401,
                'nama'                  =>  'Almaini, S.Kp., M.Kes.',
                'slug'                  =>  'almaini-skp-mkes',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'keperawatan',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4016048502,
                'id_prodi_homebase'     =>  'E13451',
                'nidn'                  =>  4016048502,
                'nama'                  =>  'Aplina Kartika Sari, S.ST., M.KL.',
                'slug'                  =>  'aplina-kartika-sari-sst-mkl',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'sanitasi',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4017028101,
                'id_prodi_homebase'     =>  '13411',
                'nidn'                  =>  4017028101,
                'nama'                  =>  'Arie Krisnasary, M.BIOMED.',
                'slug'                  =>  'arie-krisnasary-mbiomed',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4018038501,
                'id_prodi_homebase'     =>  'E13451',
                'nidn'                  =>  4018038501,
                'nama'                  =>  'Andriana Marwanto, SKM., M.Kes.',
                'slug'                  =>  'andriana-marwanto-skm-mkes',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'sanitasi',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4018048301,
                'id_prodi_homebase'     =>  'D13311',
                'nidn'                  =>  4018048301,
                'nama'                  =>  'Afriyana Siregar, S.GZ., M.BIOMED.',
                'slug'                  =>  'afriyana-siregar-sgz-mbiomed',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'gizi',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4019108201,
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  4019108201,
                'nama'                  =>  'Anang Wahyudi, S.GZ., M.Ph.',
                'slug'                  =>  'anang-wahyudi-sgz-mph',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4022036302,
                'id_prodi_homebase'     =>  'E13411',
                'nidn'                  =>  4022036302,
                'nama'                  =>  'Ahmad Rizal, SKM., M.M.',
                'slug'                  =>  'ahmad-rizal-skm-mm',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'gizi',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4027038601,
                'id_prodi_homebase'     =>  'E13451',
                'nidn'                  =>  4027038601,
                'nama'                  =>  'Arie Ikhwan Saputra, S.S.T., M.T.',
                'slug'                  =>  'arie-ikhwan-saputra-sst-mt',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'sanitasi',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  4030048402,
                'id_prodi_homebase'     =>  'D15301',
                'nidn'                  =>  4030048402,
                'nama'                  =>  'Afrina Mizawati, SST., M.Ph.',
                'slug'                  =>  'afrina-mizawati-sst-mph',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'kebidanan',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'D014',
                'id_prodi_homebase'     =>  'D13331',
                'nidn'                  =>  'D.014',
                'nama'                  =>  'Ade Sissca Villia',
                'slug'                  =>  'ade-sissca-villia',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  'promosi_kesehatan',
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L.067',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  2018089101,
                'nama'                  =>  'Agus Riyan Oktori, M.Pd.I.',
                'slug'                  =>  'agus-riyan-oktori-mpdi',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L009',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  null,
                'nama'                  =>  'Andi Aprianto, M.Ph.',
                'slug'                  =>  'andi-aprianto-mph',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L010',
                'id_prodi_homebase'     =>  198909032015041004,
                'nidn'                  =>  '0031019201',
                'nama'                  =>  'Andang Wijanarko, M.Kom.',
                'slug'                  =>  'andang-wijanarko-mkom',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L014',
                'id_prodi_homebase'     =>  'D',
                'nidn'                  =>  0000000000000,
                'nama'                  =>  'Alfina Hidayanti, SKM., MKM.',
                'slug'                  =>  'alfina-hidayanti-skm-mkm',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L018',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  null,
                'nama'                  =>  'Ahmad Azmi Nasution',
                'slug'                  =>  'ahmad-azmi-nasution',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L025',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  null,
                'nama'                  =>  'Antory Rayyen Adyan',
                'slug'                  =>  'antory-rayyen-adyan',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L030',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  null,
                'nama'                  =>  'Aplan Sarkawi',
                'slug'                  =>  'aplan-sarkawi',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L038',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  null,
                'nama'                  =>  'Anton Royan',
                'slug'                  =>  'anton-royan',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L040',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  null,
                'nama'                  =>  'Aswin Fallahudin, S.Si., M.Si.',
                'slug'                  =>  'aswin-fallahudin-ssi-msi',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L049',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  null,
                'nama'                  =>  'Andik Purwanto, M.Ph.',
                'slug'                  =>  'andik-purwanto-mph',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            [
                'nip'                   =>  'L065',
                'id_prodi_homebase'     =>  null,
                'nidn'                  =>  'L.065',
                'nama'                  =>  'Agus Mailiza, S.Si., M.Si.',
                'slug'                  =>  'agus-mailiza-ssi-msi',
                'email'                 =>  null,
                'jenis_kelamin'         =>  null,
                'jurusan'               =>  null,
                'nomor_rekening'        =>  null,
                'npwp'                  =>  null,
                'is_serdos'             =>  null,
                'no_sertifikat_serdos'  =>  null,
                'no_whatsapp'           =>  null,
                'created_at'           =>  null,
                'updated_at'           =>  null,
                'deleted_at'           =>  null,
                'is_active'             =>  1,
            ],
            ),
            );
    }
}
